name: flutter_application_1
description: Tugas UAS 06426.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  supabase_flutter: ^1.10.25
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/